server:
  port: 8085

spring:
  application:
    name: edu-agent-service
  
  # Nacos配置中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: edu
        group: DEFAULT_GROUP
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: edu
        group: DEFAULT_GROUP
        file-extension: yml
        refresh-enabled: true
        # 共享配置
        shared-configs:
          - data-id: common-config.yml
            group: DEFAULT_GROUP
            refresh: true
        # 扩展配置（服务专属配置）
        extension-configs:
          - data-id: edu-agent-service.yml
            group: DEFAULT_GROUP
            refresh: true
    config:
      import-check:
        enabled: false

  # 从Nacos加载配置
  config:
    import:
      - optional:nacos:common-config.yml
      - optional:nacos:edu-agent-service.yml
