server:
  port: 8080

spring:
  application:
    name: edu-gateway
  config:
    import: optional:nacos:edu-gateway.yml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: edu
        group: DEFAULT_GROUP
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: edu
        file-extension: yml
        refresh-enabled: true
        import-check:
          enabled: false
        extension-configs:
          - data-id: edu-gateway.yml
            group: DEFAULT_GROUP
            refresh: true